server:
  port: 8082

spring:
  application:
    name: ai-service
  config:
    import: optional:file:.env[.properties]
  model:
    chat: google-genai
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash

gemini:
  api:
    key: ${GEMINI_API_KEY}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true