'use client'
import { useState } from 'react'
import { apiPost } from '@/lib/api-client'

export default function AuthModal({ open, onClose, onSuccess }: { open: boolean; onClose: () => void; onSuccess: (token: string, role: string, email: string) => void }) {
  const [mode, setMode] = useState<'signin'|'register'>('signin')
  const [role, setRole] = useState<'CONTRIBUTOR'|'NGO'>('CONTRIBUTOR')
  const [form, setForm] = useState({ name: '', organizationName: '', domain: 'Education', email: '', password: '' })
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  if (!open) return null
  const change = (key: keyof typeof form) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm({ ...form, [key]: e.target.value })
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(''); setLoading(true); try { const data = await apiPost<any>(mode === 'signin' ? '/api/v1/core/auth/login' : '/api/v1/core/auth/register', mode === 'signin' ? { email: form.email, password: form.password } : { role, fullName: form.name, organizationName: form.organizationName, primaryDomain: form.domain, email: form.email, password: form.password }); const token = data.token || data.accessToken || data.data?.token; if (!token) throw new Error('No session token returned'); onSuccess(token, mode === 'signin' ? (data.role || data.data?.role || 'CONTRIBUTOR') : role, form.email); onClose() } catch (err) { setError(err instanceof Error ? err.message : 'Unable to authenticate right now.') } finally { setLoading(false) } }
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="auth-title"><div className="auth-modal"><button className="close-button auth-close" onClick={onClose} aria-label="Close authentication dialog">×</button><span className="eyebrow">Connecting Dots access</span><h2 id="auth-title">{mode === 'signin' ? 'Welcome back.' : 'Join the community.'}</h2><div className="auth-tabs"><button className={mode === 'signin' ? 'auth-tab active' : 'auth-tab'} onClick={() => setMode('signin')}>Sign in</button><button className={mode === 'register' ? 'auth-tab active' : 'auth-tab'} onClick={() => setMode('register')}>Create account</button></div><form onSubmit={submit} className="auth-form">{mode === 'register' && <><div className="role-switcher"><button type="button" className={role === 'CONTRIBUTOR' ? 'role-choice active' : 'role-choice'} onClick={() => setRole('CONTRIBUTOR')}>Technical Contributor</button><button type="button" className={role === 'NGO' ? 'role-choice active' : 'role-choice'} onClick={() => setRole('NGO')}>NGO Organization</button></div>{role === 'CONTRIBUTOR' ? <label>Full Name<input value={form.name} onChange={change('name')} required /></label> : <><label>Organization Name<input value={form.organizationName} onChange={change('organizationName')} required /></label><label>Primary Domain<select value={form.domain} onChange={change('domain')}><option>Education</option><option>Health</option><option>Community</option><option>Animal Welfare</option><option>Environmental Protection</option></select></label></>}</>}<label>Email Address<input type="email" value={form.email} onChange={change('email')} required /></label><label>Password<input type="password" value={form.password} onChange={change('password')} required /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button auth-submit" disabled={loading}>{loading ? 'Connecting…' : mode === 'signin' ? 'Sign in' : 'Create account'}</button></form></div></div>
}
