name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make wrapper executable (Backup)
        run: chmod +x ./mvnw

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create empty .env file for spring-dotenv
        run: touch .env

      - name: Build and test
        run: ./mvnw clean test